---

- hosts: all
  vars:
    jenkins_hostname: localhost
    jenkins_plugins:
      - ansible
    java_packages:
      - java-1.8.0-openjdk
  roles:
    - role: java
    - role: jenkins
      become: true
