---

- hosts: all
  vars:
    jenkins_hostname: localhost
    jenkins_plugins:
      - ansible
    java_packages:
      - java-1.8.0-openjdk
    nginx_vhosts:
      - listen: "80"
        server_name: "jenkins.mops.activision.com"
        return: "301 https://jenkins.mops.activision.com$request_uri"
        filename: "jenkins301.conf"
  roles:
    - role: java
    - role: jenkins
      become: true
    - role: nginx
