#!/usr/bin/env ansible-playbook -vvv

- hosts: localhost
  gather_facts: no
  vars:
    ec2_role: jenkins
    ec2_count: 1
    ec2_termination_protection: no
    ec2_iam_role: ec2_readonly
    lb_instance_port: 8080
    lb_healthcheck_path: '/'
    lb_healthcheck_protocol: "HTTP"
    lb_protocol: "HTTPS"
    ec2_private_zone: yes
    ec2_root_volume_size: 50
    ec2_instance_type: t2.micro
    ec2_monitoring: no
  roles:
    - ec2-provisioner


