#!/usr/bin/env ansible-playbook -vvv

- hosts: localhost
  gather_facts: no
  vars:
    ec2_role: jenkins
    ec2_count: 1
    ec2_termination_protection: no
    ec2_iam_role: ec2_readonly
    lb_instance_port: 80
    alb_http_routing_rule_patterns:
      - "jenkins*.mops.activision.com"
    alb_https_routing_rule_patterns:
      - "jenkins*.mops.activision.com"
    sg_ingress_rules:
      -
        proto: tcp
        ports: 
          - "{{ lb_instance_port }}"
        cidr_ip: "{{ sg_vpc_cidrs }}"
               
    lb_healthcheck_path: '/'
    lb_healthcheck_protocol: "HTTP"
    lb_protocol: "HTTPS"
    ec2_private_zone: yes
    ec2_root_volume_size: 50
    ec2_instance_type: t2.small
    ec2_monitoring: no
  roles:
    - ec2-provisioner


